# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: "Sign and release the SimdJsonSharp.Bindings package"
    runs-on: windows-latest
    steps:
      - uses: GabrielAcostaEngler/signtool-code-sign@main	      
        with:	     
          certificate: '${{ secrets.SIGNATURE_CERTIFICATE }}'	         
          cert-password: '${{ secrets.CERTIFICATE_PASSWORD}}'	          
          cert-sha1: 'SHA256'	        
          cert-description: 'Self sign SimdJsonSharp.Bindings package'	      
          folder: 'SimdJsonSharp.Bindings.dll'	       
