name: Build and Sign Assemblies

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x'

      - name: Build and Sign
        run: |
          signtool sign /f ${{ secrets.CODE_SIGNING_CERT }} /p ${{ secrets.CODE_SIGNING_PASSWORD }} /t http://timestamp.digicert.com SimdJsonSharp.Bindings.dll
        env:
          CODE_SIGNING_CERT: ${{ secrets.SIGNATURE_CERTIFICATE }}
          CODE_SIGNING_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
